### ISSUE TITLE
Change default lambda parameters of `.e`.

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#101]
I have one problem with `.e`: it by default uses `Y`. This is annoying, because some golfs can actually be made a bit shorter if I can enumerate and append to `Y`.

**Comment by isaacg1** [comment]
Do you think `Z` or `b` would work better? I don't want it to be any of `dTNGH`.

**Comment by orlp** [comment]
`b`, although I think `N` would be better.

**Comment by isaacg1** [comment]
I was leaning away from `N` because it's already used in both `V` and `o`. `b` isn't used in as much, in comparison.
