### ISSUE TITLE
Assigning variables in Defs 

### ISSUE THREAD

**Issue by jakobkogler** [isaacg1/pyth#102]
Just take a look at this: ([permalink](https://pyth.herokuapp.com/?code=DeGJ1~J1RJ%3Be1&debug=1))

    DeGJ1~J1RJ;e1

This gives a `UnboundLocalError: local variable 'J' referenced before assignment`. But strangely it works for the following example: ([permalink](https://pyth.herokuapp.com/?code=DeGJ1%2B%3DJ1RJ%3Be1&debug=1))

    DeGJ1+=J1RJ;e1

**Comment by isaacg1** [comment]
`~` doen't really work in the new system. The simple fix is to make it an alias for `+=`.

**Comment by isaacg1** [comment]
Fixed. (Not online yet.)
