### ISSUE TITLE
debug=1 Perma-Links

### ISSUE THREAD

**Issue by jakobkogler** [isaacg1/pyth#103]
Clicking on the Permalink-Button, while debug was activated, ended up in a link like: `https://pyth.herokuapp.com/?...&debug=1`. Nowadays the `&debug=1` is missing. 

The `&debug=0` is still being appended, although it has no effect at all.

**Comment by Maltysen** [comment]
Yeah, the default was changed from yes debug to no debug, and the permalink doesn't add the debug flag if it is at *what used to be* the default, but now it changed. Should be an easy fix.

**Comment by isaacg1** [comment]
Fixed.
