### ISSUE TITLE
Other Syntax Sugar

### ISSUE THREAD

**Issue by Maltysen** [isaacg1/pyth#112]
One point brought up on the [discussion for Pyth 5](https://github.com/isaacg1/pyth/issues/111) was the need for other syntax sugars, especially map. These are my thoughts right now on them, would like everyone's opinion:

- For Map we can use `A` for "apply" and take a unary, this allows a lot of things
- For Filter we have `#` cuz it kind of looks like filter ;). It doesn't seem that helpful, but it'll allow `!#`
- For the ones left over I also have some ideas
- `M` - Cummulative reduce: like reduce but returns all steps along the way. Ex `+MmO,1_1Q` is random walk.
- 'R' - Triangular map, applies unary zero times on first element, one time on second, twice on third, etc.

Any Others?

**Comment by isaacg1** [comment]
I'd like a test to see if a function leaves its input unchanged. Suppose this was `$`. `$SY` whould check if `Y` was already sorted. `$/Y2` would check if `Y` is unchanged by division by 2, i.e. if `Y` is `0` or `-1`. `$_Y` would check if `Y` is palindromic. 

Perhaps just a apply repeatedly command? `R5yY` would double `Y` 5 times, that sort of thing.

**Comment by jakobkogler** [comment]
`V` for vectorization. I think this is a really important one. 

    +V[1 2 3)[4 5 6)   => [5 7 9)
    +V[1 2 3)4   => [5 6 7)
    @Vz[1 3 1)   => [@z1@z3@z1)
    eV[10 123 ]4)   => [0 3 4)
    >V[1 5 7)[2 5 6)   => [0 0 1)
    ...

**Comment by Maltysen** [comment]
@jakobkogler maybe take it all the way and make it work on `N` dimensions?

**Comment by isaacg1** [comment]
@jakobkogler 
I've added as much of `V` as I can to Pyth - `M`, `R`, `V`.
