### ISSUE TITLE
Unnecessary characters

### ISSUE THREAD

**Issue by isaacg1** [isaacg1/pyth#114]
`A`: Equivalent to `=,`
`]`: Equivalent to `[ ... )`.
`s`: Primarily equivalent to `+F`.
`~`: Equivalent to `=+`.

**Comment by orlp** [comment]
I disagree with `]` - it's very useful and it will be more so with tuple's future removal.
I disagree even more strongly with `s` - it's ubiquitous, used in nearly every golf, often multiple times. I definitely do not want that to be a two-character code.

I'm on the fence about `~`, I think we should have a very good candidate to replace it with before considering to remove it.

I don't care about `A` at all - never used it.
