### ISSUE TITLE
Better infinities and abs.

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#115]
This is a feature available in Pyth 5, but we might want to backport for the time being.

Four overloads:

- `+)` -> `float('inf')`
- `-)` -> `-float('inf')`
- `+Z)` -> `abs(Z)`
- `-Z)` -> `-abs(Z)`

This mean we can also remove infinity from the list of mathematical constants `.n`, and remove `.a`.

**Comment by isaacg1** [comment]
I added some other things to `.a` specifically vector length, so I'm going to keep it around. The other uses don't seem common enough to warrant this, so I'll leave it out for now.
