### ISSUE TITLE
Parsing error because of `M`

### ISSUE THREAD

**Issue by jakobkogler** [isaacg1/pyth#116]
The new map operator `M` (see commit 618186026093fe12953ac69b305375c79d2d36da)  causes some problems. See for instance [here][1]. Right now I have no time for debugging. But the code works, if you checkout commit ff515ab6839d3dbfbe575d895c91727d0b146b40. 

 [1]: https://pyth.herokuapp.com/?code=M%3FsmcgtGd8fq5sm%5E-Fk2C%2CTH%5EUhQ2G1g%40Q1%3EQ2&input=8%2C1%2C2%2C0&debug=1

**Comment by isaacg1** [comment]
Fixed. There was a tiny typo leading to `wM` being intepreted as a use of the `M` operator instead of the `M` statement.
