### ISSUE TITLE
Quine Function

### ISSUE THREAD

**Issue by Maltysen** [isaacg1/pyth#118]
The quine function was rejected earlier, but now, with so many open characters/overloads available, want to try again? Or was it the cheapness of it that made us not do it?

**Comment by isaacg1** [comment]
What exactly would this function do?

**Comment by kirbyfan64** [comment]
Print the program's source code!

**Comment by Maltysen** [comment]
Well i would return it: https://github.com/isaacg1/pyth/pull/19

**Comment by orlp** [comment]
I'm not sure whether I like this. On one hand it can be used to shorten some golfs, but on the other hand on most of these golfs it's against the rules, and if it's not, it feels cheap.

**Comment by isaacg1** [comment]
One option would be to make a function which, given a string, returns that string, twice, with a `"` in the middle. If it was `.J`, a quine would be `.J".J`

**Comment by orlp** [comment]
@isaacg1 That sounds incredibly obscure and cheaty. I wouldn't feel comfortable using it in any code golf, because I think it goes against the spirit of code golf.

**Comment by isaacg1** [comment]
@orlp  Follows the letter but not the spirit, eh? Alright, I'm going to close this. I don't think there's a non-cheating way to do this well.
