### ISSUE TITLE
+= syntax for lists and dicts

### ISSUE THREAD

**Issue by jakobkogler** [isaacg1/pyth#12]
With the current syntax, adding 1 to a number in a list takes 8 chars, that's 1 more than the standart python code and 9 bytes, if you add something different

     XY1h@Y1 <-> Y[1]+=1

     XY1+3@Y1 <-> Y[1]+=3

That's really annoying, especially if you have to use this multiple times in a program. 
It would be awesome, if there would be a shorter syntax.

**Comment by isaacg1** [comment]
Fixed, see newest commit. It's a bit of a hack, but it'll work. Use X<index><list><addend>
