### ISSUE TITLE
Implicit variables for `F` and `A`

### ISSUE THREAD

**Issue by jakobkogler** [isaacg1/pyth#126]
I don't see why we need the `N` in `FNQ`. It could be implicit, like maps. And perhaps use different variables for nested loops. 

Similar `A` is really long. There's almost always a shorter version. Why not simply use implicit variables? `AQ` instead of `AGHQ`.

**Comment by isaacg1** [comment]
Implemented - `V` is what you requested for `F`, and `A` is implemented as requested.
