### ISSUE TITLE
Online Debug mode error

### ISSUE THREAD

**Issue by jakobkogler** [isaacg1/pyth#13]
I've written a program in pyth.

    Lu*GhHUb1WsPQV4J*@QNytsPQFZPQ=J/JyZ)I<JeQ XQ4-eQJ)EN XQNt@QNB

Input is 
 
    [2, 2, 3, 1, 86]

It works, when the debug mode is disabled (Output: `01120232`), but it only prints 

    ==================================================
    Lu*GhHUb1WsPQV4J*@QNytsPQFZPQ=J/JyZ)I

when debug is on.

**Comment by Tyilo** [comment]
Fixed in https://github.com/Tyilo/pyth/commit/fc83817e9c3cc0407bb979d82beed305901c5e85

Also pushed to the server.
