### ISSUE TITLE
Tutorial uses `.x`, but it doesn't reflect the current version.

### ISSUE THREAD

**Issue by MechaLynx** [isaacg1/pyth#137]
The way `.x` works has changed from when the tutorial was written and I can't find a way to create equivalent code in the current version. `.x` used to be `product()` but now is `try-except`.

**Comment by orlp** [comment]
@MechaLynx We realized the old `.x` was unnecessary, because folding multiplication (`*F`) does the same thing.

**Comment by MechaLynx** [comment]
Is there a plan to change the character set any further in the near future? I'm asking so I know if it's practical to fix the docs now, as I go through the tutorial, or wait for changes, if there are any planned.

**Comment by isaacg1** [comment]
There aren't any plans to do so, but backwards incompatible changes are made fairly often.

**Comment by MechaLynx** [comment]
That's fine. I'm not very experienced with Python though, so some cases are probably outside my reach to fix (like the `.x` one) - should I just leave the text as it is wherever I can't fix it and link to an issue or just add a note in italics indicating this no longer works?

**Comment by isaacg1** [comment]
Noting that it no longer works is fine, if you need to.

**Comment by isaacg1** [comment]
Alright, I fixed the example to use `.!`, the factorial function. Thanks for your help keeping the docs up to date.
