### ISSUE TITLE
*= producing error

### ISSUE THREAD

**Issue by iAmMortos** [isaacg1/pyth#152]
Following your documentation, I ran the code, `K1FNr1hQ*=KN;K` which is supposed to print the factorial of the user's input.
This produces the error:
`Traceback (most recent call last):`
`  File "pyth.py", line 636, in <module>`
`  File "<string>", line 6, in <module>`
`TypeError: times() missing 1 required positional argument: 'b'`

The given example `K1FNr1hQ=K*KN;K` works perfectly, but condensing the `=K*KN` to `*=KN` throws an error.

**Comment by kirbyfan64** [comment]
Try `=*KN`.

**Comment by isaacg1** [comment]
A while ago, we switched from the `*=` format to the `=*` format. I'll update the docs.

**Comment by iAmMortos** [comment]
Jolly good. Thanks
