### ISSUE TITLE
Regex matches

### ISSUE THREAD

**Issue by curiousdannii** [isaacg1/pyth#154]
It would be nice if it was possible to match regexs and extract groups from them.

As a syntax suggestion, what if `:<str><str><falsey>` was regex testing as it is now, and `:<str><str><truthy>` was matching.

---

From [PPCG chat](http://chat.stackexchange.com/transcript/message/24149481#24149481):

A list of matches would be helpful I'm sure, but it would get confusing if there was also groups within the pattern...
Maybe the third operator could specify what format the results should be in
0: count of matches
1: text of first match 
2: list of [matchedText,subgroups...] 
3: list of texts of matches 
4: list of [[matchedText,subgroups...],[],[]]
it would probably also help to get the index of the match too, maybe it could be a dict rather than a list

**Comment by isaacg1** [comment]
Implemented. https://github.com/isaacg1/pyth/commit/3573e7b9d0b7122726e01d36ffd1f5546108bb5f

Leaving this thread open for more ideas for further operations.
