### ISSUE TITLE
Online web site gives an "Internal Server Error" when the given link ends with a parenthesis

### ISSUE THREAD

**Issue by kirbyfan64** [isaacg1/pyth#158]
https://pyth.herokuapp.com/?code=&debug=0 is ok. If I add a parenthesis to the end (resulting in https://pyth.herokuapp.com/?code=&debug=0( or `https://pyth.herokuapp.com/?code=&debug=0)`), I get:

```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

Although it seems odd, this is easy to do by accident when pasting links from Markdown.

**Comment by Maltysen** [comment]
Well this occurs because the server runs `int(debug)`, which clearly won't work on `0(`.

**Comment by isaacg1** [comment]
As far as I can tell, this is really a problem, and not worth fixing. Paste a bad link, get an error page.
