### ISSUE TITLE
A few online input parsing errors

### ISSUE THREAD

**Issue by jakobkogler** [isaacg1/pyth#16]
I experienced a few errors in the online version of pyth. 

The following inputs work only in the offline version. 

Tuples:

     (1,2,3)

Nested lists, nested tuples, ...

    [[1,2,3], [1,2,3]]    

Sets:
 
    {1,2,3}

I always used `Q` as code.

**Comment by Tyilo** [comment]
Fixed in #17, also pushed to the server.
