### ISSUE TITLE
Add ceiling function

### ISSUE THREAD

**Issue by JuanPotato** [isaacg1/pyth#170]
I suggest `.C  <num>`

**Comment by isaacg1** [comment]
Seems like a good thing to add, but .C is taken

**Comment by kirbyfan64** [comment]
What about `.E` from c**E**il, which could be overloaded to take an integer value, or `.L` from cei**L**, which isn't even used yet.

**Comment by niwhsa9** [comment]
I don't know if it's taken, but how about ".r^" without the quotes. Like
round up...

On Sunday, January 10, 2016, Ryan Gonzalez <notifications@github.com> wrote:

> What about .E from c*E*il, which could be overloaded to take an integer
> value, or .L from cei*L*, which isn't even used yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/isaacg1/pyth/issues/170#issuecomment-170400498>.
>


-- 
*Ashwin*

**Comment by isaacg1** [comment]
.E sounds good to me

**Comment by isaacg1** [comment]
implemented.
