### ISSUE TITLE
Golfed way to remove empty lists in multidimensional list

### ISSUE THREAD

**Issue by benstopics** [isaacg1/pyth#171]

**Comment by isaacg1** [comment]
What about `fT`?

**Comment by isaacg1** [comment]
If that's not what you're looking for, can you give a test case?

**Comment by benstopics** [comment]
[[],[],[],[],[],[1],[],[]] => [1]

**Comment by isaacg1** [comment]
In that case, try `s` or `.n`, the two flatten functions.

**Comment by benstopics** [comment]
Nice! Thanks. New to Pyth, but great language.
