### ISSUE TITLE
"J and K don't need equals sign"

### ISSUE THREAD

**Issue by vendethiel** [isaacg1/pyth#174]
From the [tutorial](https://pyth.readthedocs.org/en/latest/simple-programs.html)

> But if you only need one variable, it’s better to use K or J which don’t need an equals sign to be assigned to:

It seems in practice, it's only true on the first assignment, and that confused me. It's said in the docs, but the tutorial might want to be updated on that particular point?

Thanks!

**Comment by isaacg1** [comment]
Fixed.
