### ISSUE TITLE
Tutorial uses old else notation

### ISSUE THREAD

**Issue by Tenchi2xh** [isaacg1/pyth#175]
In the [tutorial](https://github.com/isaacg1/pyth/blob/master/docs/simple-programs2.rst#collatz-sequence), the example uses the old notation for if-then-else: `I` and `E` instead of `I` and `.?`

**Comment by vendethiel** [comment]
Yep, I just got bit by this :/

**Comment by vendethiel** [comment]
The link [here](https://pyth.readthedocs.org/en/latest/docs.html) ("the documentation is on github") is broken as well.

**Comment by isaacg1** [comment]
Both have been fixed, thanks.

**Comment by vendethiel** [comment]
Thanks! :+1: Learning Pyth has been far easier than one would guess upfront.

**Comment by isaacg1** [comment]
I'm really glad!

**Comment by vendethiel** [comment]
not fixed, btw:

> and an else statement, E

**Comment by vendethiel** [comment]
This page: https://pyth.readthedocs.org/en/latest/spec_control.html
uses `100.T`, which it seems used to be equivalent to `100.0` then `T`.
It doesn't seem to be anymore, and thus is parsed `100` then `.T`.

**Comment by isaacg1** [comment]
Fixed, both.

**Comment by vendethiel** [comment]
Cool, thanks! :)

**Comment by JJ-Atkinson** [comment]
@vendethiel I just got bit as well ;) See here: https://pyth.readthedocs.org/en/latest/spec_control.html#e-the-else-statement
![image](https://cloud.githubusercontent.com/assets/16200906/13030996/44fa0818-d282-11e5-8af9-12df1557a132.PNG)
