### ISSUE TITLE
builtin "product"? (F <pfn> missing from docs)

### ISSUE THREAD

**Issue by vendethiel** [isaacg1/pyth#178]
we have "s" as sum, but product is very useful as well. it'd be nice to have a builtin for it?

**Comment by jakobkogler** [comment]
You can do `*F[2 3 5`. This is already really short. 

This obvioulsy doesn't handly the special case of an empty product.

**Comment by vendethiel** [comment]
This might be missing in the docs, no? I don't see a `F <pfn>`?

**Comment by isaacg1** [comment]
Correct, it is missing in the docs. Will fix.

**Comment by vendethiel** [comment]
Thanks you :heart:

**Comment by isaacg1** [comment]
Fixed.
