### ISSUE TITLE
Inclusive range doesn't provide decrementing values

### ISSUE THREAD

**Issue by syrrim** [isaacg1/pyth#181]
`}`, the inclusive range function, should continue to work when A > B. In this case, it would provide [A, A-1, ... B+1, B]. This would put in line with `r`, the half inclusive range function.

**Comment by muddyfish** [comment]
Added a  [pull request](https://github.com/isaacg1/pyth/pull/183) with this functionality.

**Comment by isaacg1** [comment]
Merged.
