### ISSUE TITLE
Feature request (regex)

### ISSUE THREAD

**Issue by kckennylau** [isaacg1/pyth#185]
- `a*` matches **0** or more instances of `a`.
- `a+` matches **1** or more instances of `a`.
- should we have a character that matches **2** or more instances of `a`?

**Comment by Maltysen** [comment]
uhhh, we use the python `re` module for this, so I'm not sure we can do much with this. Also `{2,}` does what you want.

**Comment by kckennylau** [comment]
Well, thanks for your quick reply. Maybe you could translate the regex, so that `\S#` (for exmaple) becomes `\S\S+`.

**Comment by isaacg1** [comment]
`\S{2,}` is the same as `\S\S+`.

That being said, Pyth's regexes are exactly the same as Python's, and this is not a good place for asking for advice on using Python regexes.
