### ISSUE TITLE
Implicit Input Inside Lambdas

### ISSUE THREAD

**Issue by Maltysen** [isaacg1/pyth#190]
The implicit `Q` is really nice, but I feel that inside lambdas like `m` it really isn't appropriate. For example, `mhs{*MyP`. This will take implicit input from `Q`, but it is very rare that I would want the `P` to also take from `Q`.

So I propose that inside lambdas, when closed with `;` or `EOF`, that the implicit input should not be `Q` but instead the innermost lambda var. For instance, the above example would expand to `mhs{*MyPdQ`

**Comment by isaacg1** [comment]
This is great, I like this a lot.

**Comment by isaacg1** [comment]
Implemented
