### ISSUE TITLE
F on arity 1 functions

### ISSUE THREAD

**Issue by isaacg1** [isaacg1/pyth#195]
Currently, F does nothing on <pfn1>. A proposal for

**Comment by isaacg1** [comment]
what it could do was to apply the given function to the input a given number of times.

**Comment by Maltysen** [comment]
How about having the parser detect that the op is arity one and then taking an additional argument. Like for our motivating example, it would be `.!F3 2` would work because the parser would make `.!F` consume 2 args.

**Comment by isaacg1** [comment]
Implemented.
