### ISSUE TITLE
=s.TQ assigns to T rather than Q

### ISSUE THREAD

**Issue by andersk** [isaacg1/pyth#201]
`=s.TQ` compiles to `assign('T',Psum(transpose(Q)))`, even though `T` is not mentioned. Shouldn’t that assign to `Q`?

**Comment by Maltysen** [comment]
that's very weird. even `=.TQ` compiles properly, its only when you put something before it that this bug pops up.

**Comment by Maltysen** [comment]
the same thing happens with things like `=S.ZQ`. might be a problem in the parser.

**Comment by Maltysen** [comment]
But it doesn't happen with `=S.!Q` or `=S.aQ` where there isn't a variable called `!` or `a`.

**Comment by isaacg1** [comment]
Another case of the same bug: https://pyth.herokuapp.com/?code=%3D%2a"blah"Tb&debug=1

To fix this, what Pyth really needs is a tokenizer

**Comment by isaacg1** [comment]
This is fixed.
