### ISSUE TITLE
Feature request - f g f^-1

### ISSUE THREAD

**Issue by kckennylau** [isaacg1/pyth#202]
(todo: elaborate)
If the new command is named `.G`:

`.G  <pfn><n-1:any><l:d><any> A^-1(C(A(D,...)))`

For example, if I would like to add 100 to Q, multiply by 3, then subtract 100:

`+.G100*3dQ`

Reference: [the `&.` operator in J](http://code.jsoftware.com/wiki/Vocabulary/ampdot)

**Comment by isaacg1** [comment]
This seems like it would be unfeasible, since pyth doesn't have a concept of an inverse of a functino, unlike J. Do you have any ideas for how to implement this?

**Comment by kckennylau** [comment]
Define the inverse of each function, and if a particular function has no inverse, then throw an error.

**Comment by isaacg1** [comment]
I'm not planning on implementing this, though if someone else did, I'd welcome it.
