### ISSUE TITLE
REPL when no flags are set, and execute code from stdin

### ISSUE THREAD

**Issue by FliiFe** [isaacg1/pyth#208]
The current behavior for the interpreter is to enter REPL mode when no argument is given, but you can't give code directly to stdin.
For example, this
```bash
$ ./pyth.py <<<'"Hello'
```
or
```bash
$ echo '"Hello' | ./pyth.py
```
Will output this : 
```
Welcome to the Pyth REPL.
Each input line will be compiled and executed, and the results of
each one will be passed into the next one's input stream.

>>> Hello
>>>
```
That is not a desired behavior.

So, could we execute code from stdin ?

**Comment by FliiFe** [comment]
So, judging by the code, it looks like this behavior is not wanted.
This is the code : 
```python
    # Check for command line flags.
    # If debug is on, print code, python code, separator.
    # If help is on, print help message.
    if (len(sys.argv) > 1 and
            "-r" in sys.argv[1:] 
            or "--repl" in sys.argv[1:]) \
            or all(flag in ("-d", "--debug") for flag in sys.argv[1:]):

        Repl("-d" in sys.argv[1:] or "--debug" in sys.argv[1:]).cmdloop()
```
However, to check for actual command line flags, the check should be `len(sys.argv) > 2`, because the first element of sys.argv is the script name, and, AFAIK, is always present (thus keeping a minimal length of 1).

**Comment by isaacg1** [comment]
I like the behavior of entering the REPL with no flags. I agree that the code is written incorrectly (len(sys.argv) > 1 is unnecessary and placed wrong). If you want to execute code, you can just use `-c`, what's wrong about that?

**Comment by isaacg1** [comment]
I remvoed that unnecessary check you mentioned.
