### ISSUE TITLE
Assign Operator Bug

### ISSUE THREAD

**Issue by Maltysen** [isaacg1/pyth#21]
The assign operator's entry in data.py has a bug that prevents it from being used. It says 'A': '=,{0}{1}' instead of 'A': ',{0},{1}' There is a missing comma.

**Comment by isaacg1** [comment]
I believe `A` is currently working as intended. Here is an example program using `A`: `AYZ,ZYYZ`. This swaps the values stored in `Y` and `Z`, leading to `0` in `Y` and `[]` in `Z`. Please leave a comment with a piece of code you believe is not functioning correctly, so I can determine whether a bug exists or not.

**Comment by Maltysen** [comment]
Ah, sorry. I misunderstood how A was supposed to be used, and assumed the syntax `AkdTZ` would be enough to do `k=10` and `d=0` and no separating comma was necessary. Is there any particular reason this is not so?

**Comment by isaacg1** [comment]
It's so you can assign an existing tuple using A.
