### ISSUE TITLE
Backslashes error in third argument of substitution

### ISSUE THREAD

**Issue by kckennylau** [isaacg1/pyth#211]
[`:z"b""\\"`](http://pyth.herokuapp.com/?code=%3Az%22b%22%22%5C%5C%22&input=abc&debug=0) does not work but [`:z"b""d"`](http://pyth.herokuapp.com/?code=%3Az%22b%22%22d%22&input=abc&debug=0) works.

I've also tried [`:z"b""\\\\"`](http://pyth.herokuapp.com/?code=%3Az%22b%22%22%5C%5C%5C%5C%22&input=abc&debug=0) which also does not work.

**Comment by kirbyfan64** [comment]
FWIW, `:z\b\\` is shorter and has the same effect.

**Comment by isaacg1** [comment]
Pyth's online interpreter blacklists lots of stuff to prevent hacking. Unfortunately, it's a little overzealous. Maybe someday we'll fix this, like with a sandbox system, but it's not something I'm going to work on.
