### ISSUE TITLE
The documentation does not specify the difference between J and K

### ISSUE THREAD

**Issue by Zer0Zer0Huit** [isaacg1/pyth#222]
The behaviors of J and K are slightly different. J is assigned with copy while K is assigned directly. The documentation in [rev-doc.txt](https://github.com/isaacg1/pyth/blob/master/rev-doc.txt) does not specify this difference:
`J  <any>                  Variable, Autoinitializing. J=A on first use.`
`K  <any>                  Variable, Autoinitializing. K=A on first use.`

**Comment by isaacg1** [comment]
J and K at one point had different behaviors, but do not any longer. The docs reflect this fact. You can see that they are identical by looking at the compiler Python code:

```
==================== 4 chars =====================
K4J4
==================================================
assign("K",4)
assign("J",4)
==================================================
```
