### ISSUE TITLE
Feature-request: Add a function that duplicates a sequence

### ISSUE THREAD

**Issue by Mr-Xcoder** [isaacg1/pyth#237]
If I want to duplicate a String (i.e. append a copy of itself to it, e.g.: `ABCD` -> `ABCDABCD`), I have to write `*2"ABCD`. I think this should be a one-byte built-in, like `y` is to `*2<num>`. That would be helpful, especially in tasks involving String manipulation.

**Comment by isaacg1** [comment]
What one character operation do you think this is more useful that, which we should remove?
