### ISSUE TITLE
Online interpreter does not work

### ISSUE THREAD

**Issue by nim-ka** [isaacg1/pyth#259]
Try `h"hi"`. It errors:
```
Traceback (most recent call last):
  File "pyth.py", line 771, in <module>
  File "<string>", line 3, in <module>
  File "/app/macros.py", line 726, in head
  File "/app/macros.py", line 30, in is_seq
  File "/app/.heroku/python/lib/python3.7/collections/__init__.py", line 48, in __getattr__
ImportError: __import__ not found
```

**Comment by nim-ka** [comment]
http://pyth.herokuapp.com/?code=h%22hi%22&debug=0

**Comment by haselkern** [comment]
Yup, can confirm. The simple example `yU3` from the documentation throws a similar error:

```
Traceback (most recent call last):
  File "pyth.py", line 771, in <module>
  File "<string>", line 3, in <module>
  File "/app/macros.py", line 1178, in subsets
  File "/app/macros.py", line 34, in is_col
  File "/app/.heroku/python/lib/python3.7/collections/__init__.py", line 48, in __getattr__
ImportError: __import__ not found
```

**Comment by jakobkogler** [comment]
Yeah, the problem is confirmed. I already made a fix for it, however @isaacg1 needs to accept and deploy it.

**Comment by Maltysen** [comment]
It turns out that i really can't live without Pyth in my daily life (I can't count how many times I've tried to run some script before getting stopped by this bug in the last couple of weeks), so i've uploaded @jakobkogler's fix to http://pythtemp.herokuapp.com/. This is a strictly temporary measure until @isaacg1 accepts the PR.

**Comment by GolfingSuccess** [comment]
@Maltysen Hey, I can also confirm the issue! Thanks for the temporary solution.

**Comment by GolfingSuccess** [comment]
So, it looks like the issue isn't currently present, although no change has been made yet.

**Comment by jakobkogler** [comment]
No, still broken.

**Comment by GolfingSuccess** [comment]
[Not for me...](http://pyth.herokuapp.com/?code=1&debug=0)

**Comment by jakobkogler** [comment]
The error doesn't occur for every code. Try one of the examples mentioned above. Those still don't work.

**Comment by GolfingSuccess** [comment]
Something has improved for now, since it did occur for e.g. `z`, but it doesn't anymore.

**Comment by akleemans** [comment]
**Working online interpreter**: https://pyth-docker.azurewebsites.net/

As neither the original interpreter nor the version by Maltysen work anymore I decided to host a version myself.
I created a docker image (see forked Repo https://github.com/akleemans/pyth-docker) with updated dependencies (based on Python 3.11) if anybody wants to run it by themselves.

**Comment by Maltysen** [comment]
@akleemans tsym!

**Comment by isaacg1** [comment]
@akleemans Thanks for getting it running!
