### ISSUE TITLE
Splitting lists into parts

### ISSUE THREAD

**Issue by jakobkogler** [isaacg1/pyth#26]
During [this](http://codegolf.stackexchange.com/questions/48027/discrete-bakers-map) golfing competition, I needed to split a list (or string) into two parts. Instead of `cY/lY2` (calculating half the length and chopping) `c2Y` would be nice. `c <int> <list>` is not used at the moment. 

I've already forked the project and did the changes. But before making the push-request, I just wanted to know your opinion on how to handle the case, when the integer is not a divisor of the length. 

There are two approaches: 

 - Split into equal parts, only the last one is a shorter. E.g. `c3UT` would yield `[0, 1, 2, 3], [4, 5, 6, 7], [8, 9]`. The ugly part is, if the integer is greater than half the length, it nevertheless splits it into half the length parts. E.g. `c7UT` would give `[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]`. 

 - Split into parts, so that the last few parts are one shorter than the first parts. E.g. `c3UT` would yield `[0, 1, 2, 3], [4, 5, 6], [7, 8, 9]`. This handles the ugly part of the first approach better: `c7UT` would give `[0, 1], [2, 3], [4, 5], [6], [7], [8], [9]`

What do you think?

**Comment by isaacg1** [comment]
Hmm.. One option is `c7UT` would give `[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [], []`. Nevertheless, I prefer the later option, but again with empty lists at the end if necessary. `c12UT` would give `[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [], []`
