### ISSUE TITLE
Invert dictionary using _

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#29]
A cool feature would be to allow `_` to be used on dictionaries, inverting the dictionary:

    H = {v: k for k, v in H.items()}

Right now `_H` is always an error, as `H[::-1]` makes no sense.

**Comment by isaacg1** [comment]
I like it. Will implement. I'm also going to add a 'convert to dictionary' operation in place of `~`, since dicts a realm of unexplored possibilities.
