### ISSUE TITLE
Use ._ as secondary operation table

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#30]
What if we turned `._` where _ is `[^0-9]` into a secondary operation table indexed by _? This would be easy to parse, wouldn't break old programs, and add a plethora of possibilities.

The only annoying thing about using `.` is that you'll have to implement lookahead when encountering `.` to check if the next token is `[^0-9]` in order to see if it's part of a numeric literal or an operation. But this isn't too complex.

For example `.a_` could translate to `abs(_)`.

Functions that could get a place in this table that are missing right now (and that aren't short already) from the top of my head:

- `abs`
- `any`
- `all`
- `bin` (I'd suggest with `0b`)
- `enumerate` (`.e_~` -> `map(lambda imp_defined: (lambda: G, H: ~)(*imp_defined), enumerate(_)):`)
- `hash`
- `hex` (I'd suggest with `0x`)
- `range` with step
- `random.shuffle`
- `round`
- `itertools.permutations`
- `itertools.combinations`
- `itertools.combinations_with_replacement`
- `math.log`
- `math.sin` (and friends)
- binary and (`.&`)
- binary or (`.|`)
- ~~binary not (`.~`)~~ (this one isn't actually shorter than `t_`)

Constants that might be useful

- `float("inf")`
- `math.pi`
- `math.e`

**Comment by isaacg1** [comment]
Sounds like a great idea - I'm going to start with the python builtins that can be directly dropped in, then eventually expand to include all of these.

However:
max = eS
min = hS

**Comment by orlp** [comment]
@isaacg1 You're right about max, min, so I'll remove those.

**Comment by orlp** [comment]
@isaacg1 If you have ideas for any utility functions/builtins do let me know :)

**Comment by isaacg1** [comment]
I'm planning to look through a bunch of packages to find good ones.

**Comment by orlp** [comment]
@isaacg1 I'd also suggest reverting the `~` dict change, and stashing that under some `._` command, as `~` was rather useful (at least to me) and it would invalidate old answers.

**Comment by isaacg1** [comment]
Sure, though primarily from the `Don't break stuff` side. It only saved 1 character.

**Comment by orlp** [comment]
@isaacg1  I was under the impression it saved two?

`=Z+Z42` vs `~Z42`

**Comment by isaacg1** [comment]
`+=Z2` was recently added, along with `_=` anything.

**Comment by orlp** [comment]
@isaacg1 Oh, I wasn't aware, cool.

**Comment by isaacg1** [comment]
Alright, initial version implemented.

**Comment by orlp** [comment]
@isaacg1 I spotted a bug in your parsing - I'll fix it.

Also, I was thinking `.x` instead of `.H` for `hex`, thoughts?

**Comment by isaacg1** [comment]
`.x` makes me think of `exec` for than `hex`, so I decided to avoid it. `.R` is `round` to leave `.r` for 3 arity range.

**Comment by orlp** [comment]
@isaacg1 I just realized that for the best behavior in the future we must make one sacrifice that could *potentially* break programs (I don't think it will affect many).

`5.H5` should print 5 0x5, not 5. {} 5. The reason is that the latter behavour can always be forced by `5.0H5`, but `5 .H5` would supress auto-printing.

**Comment by isaacg1** [comment]
I agree, though for a somewhat different reason: I think that the ._ usage will be more relevant, adn so should be the default. Floats don't get used that often.

What was the parsing bug you mentioned earlier?

**Comment by orlp** [comment]
@isaacg1 It was the assertion :)

I'm also working on the code, you're pushing too fast :(

**Comment by isaacg1** [comment]
Sorry about that. If it helps, I'm done for the night, so you can work in peace.
