### ISSUE TITLE
Unpacking requires close-parentheses

### ISSUE THREAD

**Issue by jakobkogler** [isaacg1/pyth#34]
I have one issues/proposal about the new unpacking operator. Since the compiler doesn't know the size of the iterable, it gets a little bit confused.

It works great, if you only do one statement: [`+.*,5 7`][0] prints 12. 

It after the code segment a second statement follows. You need a close-parentheses: [`+.*,5 7)Y`][1]. If you write [`+.*,5 7Y`][2], the parser thinks that `.*,5 7` is the first argument of `+` and `Y` is the second and prints the error message `SyntaxError: only named arguments may follow *expression`. 

I think the close-parentheses should be implicit. You can only use the unpacking as the last (or the last few) arguments in a function call. Something like `f(*x, 2)` doesn't work (it also doesn't work in Python!). So at the moment you always have to write a close-parentheses after the unpacking. There's just one special case...

This is one of nicest features about the unpacking. You can now do [`AG.*HUTGH`][3]. I think this statement is the only example, where an implicit close-parentheses would be wrong. 

  [0]: https://pyth.herokuapp.com/?code=%2B.*%2C5+7
  [1]: https://pyth.herokuapp.com/?code=%2B.*%2C5+7)Y
  [2]: https://pyth.herokuapp.com/?code=%2B.*%2C5+7Y
  [3]: https://pyth.herokuapp.com/?code=AG.*HUTGH

**Comment by orlp** [comment]
I totally agree. I was actually about to open this exact issue when I clicked here.

For now I'd suggest the solution of adding a second operator that substitutes itself for `.*)`. There might still be more use cases of `.*` without the implicit parentheses.
