### ISSUE TITLE
Autoinitializing input variable bug 

### ISSUE THREAD

**Issue by jakobkogler** [isaacg1/pyth#39]
It seems like the autoinitializing input variables are a bit buggy. Here three examples I found: 

 - [`"A horde of zombies are attacking!"z"RUN"`][0] doesn't read any input, instead it stores the string `RUN` in the variable `z`. This one is actually documented in the code: "First occurance must not be in a string." 

 - Some ascii art: [`"._.-\"-._."z"._.-\"-._."`][1]. Again this doesn't read any input and only stores the second string in `z`. There are 3 quotation marks before the first occurrence of `z`, so one of the parser thinks that `z` is part of a string. This one is not documented. 

 - [`+\\\z`][2] prints correctly `\z`, but only if the input isn't empty. One of the parser only looks at the last two chars before `z` and therefore interprets them as escaped `\`. It doesn't see, the last two chars are not part of the same statement. Also not documented. 

Of course I forced the errors in all these examples and such errors are quite unlikely to happen in real live. But the first example (of course in a different code) happen to me today. 

  [0]: https://pyth.herokuapp.com/?code=%22A+horde+of+zombies+are+attacking!%22z%22RUN%22&input=No+chance&debug=0
  [1]: https://pyth.herokuapp.com/?code=%22._.-%5C%22-._.%22z%22._.-%5C%22-._.%22&input=Fail&debug=0
  [2]: https://pyth.herokuapp.com/?code=%2B%5C%5C%5Cz&debug=0

**Comment by orlp** [comment]
I don't think that "First occurance must not be in a string." is desired behaviour, ever.

**Comment by jakobkogler** [comment]
@orlp Yeah, I think so too. It was probably just a quick workaround.

**Comment by isaacg1** [comment]
Yeah, this was not intended behavior, just laziness / a hack.

**Comment by isaacg1** [comment]
Another thing we'll have to be sure not to introduce/build in a case for is .z, or .Q

**Comment by orlp** [comment]
@isaacg1 All issues should be simple to resolve if you treat `z` and `Q` and co like proper tokens, and only do their thing when you encounter the token.

**Comment by isaacg1** [comment]
True, and perhaps that would be better. However, that would require the parser to allow global effects on the code, which I'd prefer to avoid until it's really necessary.

**Comment by jakobkogler** [comment]
@orlp Pretty sure this would break lot's of existing code. And all 3 issues have been fixed in #40.

**Comment by orlp** [comment]
@jakobkogler Could you give an example?

**Comment by jakobkogler** [comment]
@orlp It may break, if you use `z` and `Q` in the same code. At the moment the first line of the input is always stored into `z`, and the second line in `Q`.

It would break for instance this one ([link](http://codegolf.stackexchange.com/questions/47710/the-characters-in-the-string-go-round-and-round/47719#47719)), since `Q` appears before `z`. (Swapping the input lines fixes it of course.)

It get's even worse if you additionally read input with `w`. For instance I've used `#aYw)` to read multiple lines of input. At the moment you can easily do `#aYw)m"do stuff with Y"Q`, which reads the first line of the input and stores it in `Q` and afterwards read additional lines and saves them in `Y`. With your approach you would have to do something like. `JQ#aYw)m"do stuff with Y"J`.

**Comment by jakobkogler** [comment]
@isaacg1 While I'm on the subject of reading multiple lines of input and you mentioned `.z`. That would be a nice addition.

**Comment by isaacg1** [comment]
What were you thinking of for `.z`?

**Comment by jakobkogler** [comment]
Well, reading multiple lines (read all of the input). The same as `#aYw)` does. 

For instance check out the new [How do I get more Klotski in my life?](http://codegolf.stackexchange.com/questions/48236/how-do-i-get-more-klotski-in-my-life) challenge. It would be quite nice, if you could input 

    #######
    #001gg#
    ##.222#
    .######

instead of 

    #######\n#001gg#\n##.222#\n.######

First of all it's easier to develope the program, since you can quickly test multiple inputs without adding the `\n`s. 

And secondly `.z` would also be shorter, if your doing `#aYw)` (multiple line input) or `cQb` (single line input like `"a\nb\nc"`).

**Comment by orlp** [comment]
@jakobkogler No you misinterpreted what I meant.

My exact proposal is the following:

> When we encounter the __token__ `z`, `Q` save a boolean flag that we encountered the respective token. After all code has been generated prepend the autoinitialization code for `z` and `Q` if their respective boolean flags are true.

**Comment by isaacg1** [comment]
@jakobkogler Implemented .z and .Q
