### ISSUE TITLE
Can't make empty set.

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#41]
Please allow `{)` to make an empty set by making the argument to `Pset` optional.

I am aware of `{Y`, but `Y` is not always empty.

**Comment by isaacg1** [comment]
Implemented.

**Comment by orlp** [comment]
Could you do the same for `[)`?

**Comment by isaacg1** [comment]
Sure, and I'll throw in `()` for free. I'm going to make `])` `[[]]`, though, because that case also comes up a fair amount.

**Comment by isaacg1** [comment]
Hang on, `[)` and `()` already work.

**Comment by orlp** [comment]
Allright, cool, then it was just set that was the oddball :)
