### ISSUE TITLE
Should cast seq to set for .& and .|.

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#42]
For `.&` and `.|` we should cast sequences to sets before doing `&` or `|`. It's the only sensible thing to do, and a syntax error right now.

**Comment by isaacg1** [comment]
What would distinguish `.&` from `@`? I can implement the equivalent of `@` for union for `.|`, though.

**Comment by orlp** [comment]
@isaacg1 `.&` is mostly for bitwise and, and currently directly maps to `&`, which is union for sets, hence this suggestion. Maybe we should do something entirely different for `.&` when an argument is a sequence. I did spot a quick potential annoyance, if argument `a` of `@` is a set, it will still return a list, rather than a set.

**Comment by isaacg1** [comment]
Alright, I'm working on this. Implementing union, (`.|`) and fixing the behavior of `@`.

**Comment by isaacg1** [comment]
Implemented.
