### ISSUE TITLE
a should be add on sets.

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#43]
When the argument to `a` is a set, currently it will try to use `append` which is obviously a syntax error. I propose that `a` means `add` on sets.

**Comment by orlp** [comment]
Oh and very important, if you attempt to add a mutable sequence to a set, I'd suggest we automatically cast to a `tuple` rather than throwing an error.

**Comment by isaacg1** [comment]
Working on implementing.

**Comment by isaacg1** [comment]
Implemented.
