### ISSUE TITLE
Indexed += on dicts should act like defaultdict.

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#44]
If you use `X` with `b` as a `dict` then the code will act as if you've written:

    b[a] += c

I'd propose the following behaviour instead:

    try:
        b[a] += c
    except KeyError:
        b[a] = c

**Comment by isaacg1** [comment]
Sounds good to me. Will implement, and will push once github stops being DDoS'd.

**Comment by isaacg1** [comment]
Implemented.
