### ISSUE TITLE
Pyth Test Suite

### ISSUE THREAD

**Issue by isaacg1** [isaacg1/pyth#46]
Pyth is getting large enough that it should probably have a test suite. We would want this to cover every construct in the language, getting called with each type in the language. Tests for the parser itself would also be good.

Questions:
Should this be tested in python, by calling the functions in `macro.py`, or should this be done outside of that, by looking at the output of `pyth.py `?
What's a good way to make this easily extensible?
Are there good testing packages for Pyth that should be used?

**Comment by orlp** [comment]
Definitely do _not_ make this by directly calling macro.py - test programs directly.

My suggestion to write the test cases is to make an array of 3 tuples `(program, input, output)`, and replace the Python functions `input()` and `print()` to test.

Since all testing will be uniform like that - program, input, output - I wouldn't suggest using a testing framework just yet, and just loop over all tests and print a test if it fails.

**Comment by isaacg1** [comment]
I didn't know `input()` and `print()` could be replaced like that - how would one go about doing that?

**Comment by orlp** [comment]
old_print = print
    def print(*args, **kwargs):
        old_print("You have no power here!")

**Comment by isaacg1** [comment]
ll right, I'm working on implementing this.

**Comment by isaacg1** [comment]
How does the current system look?

**Comment by orlp** [comment]
I do not think this is the right way to do it. Opening a lot of processes is slow and not cross-platform either.

Just pass the programs to `general_parse` and replace `input()` and `print()`.

**Comment by orlp** [comment]
On a side note, now that we have tests, a webserver, docs, etc, I'd suggest we'd introduce some file structure rather than dump everything in the project root.

On a similar note, does the `programs/` folder have any particular use?

**Comment by isaacg1** [comment]
The programs folder hypothetically was going to be where I put interesting programs I wanted to share, but that didn't pan out. The current system is rather slow, the implementation you're suggesting is probably better. If you want to implement it, that would be appreciated.

**Comment by orlp** [comment]
I'll write a function that allows you to run an arbitrary program with an input and get its output. Then we can use that function in the webserver and in the tests. This would make both the tests and the webserver portable.

Then, would you agree with this file structure?

server/server.py
server/favicon.ico
server/index.html
server/web-docs.txt
pyth/data.py
pyth/extra_parse.py
pyth/macros.py
pyth/\__init__.py
.gitignore
LICENSE
README.md
doc.txt
pyth.py
test.py

Then for the following files:
- programs - Remove or move to Github wiki.
- types.txt - Remove or move to wiki and update.
- how-to-use-pyth.txt - Either remove or move into wiki or readme.

And a second branch, called heroku, should be made containing the following _additional_ files:
- Procfile (with command updated to `web: gunicorn --pythonpath server server:app`)
- runtime.txt
- requirements.txt

**Comment by isaacg1** [comment]
The file structure looks good, and programs and types can be removed, with how to use moved into the readme. I'd prefer to keep everything on one branch for ease of updating, so how about moving the heroku files into the server file as well?

**Comment by orlp** [comment]
@isaacg1 I never used heroku, but I think those file have to be in the root - hence my suggestion of a different branch.

However ease of updating shouldn't be harder at all, after setting up the branch once:

    git checkout heroku && git merge . master && git push heroku heroku:master && get checkout master

**Comment by isaacg1** [comment]
Fair enough, I didn't realise their were required to be in root.

**Comment by Maltysen** [comment]
If we're making branches, how bout a branch for the cheese shop. Right now I am setting bash aliases to avoid having to navigate to the correct folder, but we should provide a command line script to put on pypi. Here is a tutorial on that: http://www.scotttorborg.com/python-packaging/command-line-scripts.html. I would do it myself, but you should be the one to register it. The name ``pyth`` is taken so I recommend ``pyth-lang``.

In that branch we would be keeping all the core functionality and keep a setup.py outside. No server stuff, PROCFILE, etc.

**Comment by orlp** [comment]
What is a cheese shop?

**Comment by Maltysen** [comment]
Oh thats the monty-python-referential name for [Pypi](https://pypi.python.org/pypi). Look at the conversation at the bottom. ;P

**Comment by jakobkogler** [comment]
I wrote some tests today and I'm not really happy about the current testing system. 

The main problem I encountered is, that Pyth programs doesn't always return the same output. For instance when you use sets, dicts, random numbers, shuffle, ...

**Comment by orlp** [comment]
@jakobkogler The random output can be solved by re-seeding with a known seed before every test case. Alternatively you could set up a different set of tests that will be run with a plethora of different (but constant) seeds to prevent getting 'lucky'.

As for sets/dicts, perhaps we should change `Pprint` to always print them ordered?
