### ISSUE TITLE
Only use next lambda parameter if nested.

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#49]
This is a pretty big backwards-compatibility break, but I think lambda parameters should only switch to the next set of parameters if you're nesting them.

**Comment by isaacg1** [comment]
I agree, that would be really nice, and definitely worth breaking compatibility. I'm not completely sure how to go about doing it, though. Perhaps pass an extra parameter in parse, containing all of the nesting levels?

**Comment by orlp** [comment]
Basically this requires a manual stack or recursive descent parsing.

It would be quite some work to port the parser into a recursive descent, but it should make this issue trivial, and make the code a lot cleaner in the end (a lot less exceptions, and different tables for different kinds of operators).

**Comment by isaacg1** [comment]
Alright, I've implemented this. It was actually quite simple. I'm going to push it, and update the release number to 4.0
