### ISSUE TITLE
Adding complex numbers to Pyth.

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#51]
It's been suggested a couple of times now. I'm opening this issue to talk about how complex numbers would be implemented, and what behaviour we want from existing functions when passed in a complex argument.

**Comment by orlp** [comment]
I'd like to start off with the most basic functionality. I think complex numbers should be implemented through the default complex type.

- We need a complex number constructor, `.jab` with a real and b imaginary (`a + bj`) seems fine for that.
- `-+*^_` should work as expected.
- `c` should work as expected, but I don't know what we should expect of `/`.
- We could compare magnitude with `<` and `>`.
- I'd suggest that https://github.com/isaacg1/pyth/issues/52 be implemented, and work just fine with complex numbers.
- I don't know what `%` should do for complex arguments.
- `.a` should give magnitude.
- `.l` should be complex logarithm.
- I have no idea what `.s` should be.

Arity 1 functions that we could overload for complex numbers: `CPSUelsv`
Arity 2 functions we could overload for complex numbers: `gijrx`

I didn't bother listing the `.` functions, as it's pretty much all of them, and we should fill up the above ones first anyway.

**Comment by Maltysen** [comment]
A lot of the things you mentioned work already. The 6 basic arithmetic ops work already (``c``, not ``/``), absolute values work, ``.a`` works, we have to implement comparison by magnitude. All the other functions can we used if we just import ``cmath`` instead of ``math``. This will not result in problems with reals, except that it will always return a complex, with reals it will just have 0 for ``imag``. The fix is easy, just make ``Pprint`` special-cased for complexes with 0 as imag, itll just print real.

**Comment by orlp** [comment]
@Maltysen That's a hacky fix. A much better fix is to only use the `cmath` function if one of the arguments is complex.

**Comment by isaacg1** [comment]
I'm thinking we leave out `/` for now, have `%` apply to the real part and the imaginary part separately. We also want the `phase`, `polar`, `.real`, `.imag`, and `conjugate` methods.

**Comment by jakobkogler** [comment]
`.jab` is quite lengthy. I'm not sure how often you would need complex numbers and in which ways you need it. 

The only time I would have enjoyed complex number was in this golfing contest: [Magnetic Sculptures… in Space!](http://codegolf.stackexchange.com/a/45121/29577). Here I only needed the complex number `0 + 1j`, twice. So here I would really like a 0-arity command. `.jZ1.jZ1` are 8 chars, `K.jZ1KK` are 7 chars, `.j.j` only 4. 

Of course you can easily generate all other complex numbers with `+a*.jb`. O.k. that are way too many chars. What about `.i` for `0 + 1j` and `.jab` for `a + bj`?

**Comment by isaacg1** [comment]
Another alternative would be to set up the default values of `.j` so that `.j)` = `0 + 1j`

**Comment by isaacg1** [comment]
Implemented.
