### ISSUE TITLE
Enumerate is not implemented.

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#56]
The function `Penumerate` simply does not have the functionality implemented for enumerate.

**Comment by orlp** [comment]
https://github.com/isaacg1/pyth/pull/57

**Comment by isaacg1** [comment]
Thanks for point this out. The functionality was accidentally removed in this commit: https://github.com/isaacg1/pyth/commit/fe6588e7b124560bd373e2b3c7d6207ae203d960
And has been restored.
