### ISSUE TITLE
Make .z and .Q autoinitializing variables.

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#59]
You can't ever sanely use `.z` or `.Q` twice, so it would be better if they were autoinitializing variables.

It's important that `z` and `Q`, if used, are initialized before `.z` and `.Q`, and if `.z` and `.Q` are both used they should both refer to the same data, only `.Q` would be `eval`'d.

**Comment by isaacg1** [comment]
There's a bunch of places in the code that assume variables are one character, so this might take a while.

**Comment by orlp** [comment]
@isaacg1 As a temporary solution could we at least make calling `all_input` and `eval_all_input` return the same value everytime, caching the result after the first call?

**Comment by isaacg1** [comment]
Sounds quite reasonable.

**Comment by orlp** [comment]
I'll do it - writing commits ATM anyway.

**Comment by orlp** [comment]
Woops, shouldn't close as it will only be temporarily solved.

**Comment by isaacg1** [comment]
Now that we can assign things inline, these don't really need to be variables - `J.zJ` is the same length as `.z.z` would be.
