### ISSUE TITLE
Distance function?

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#62]
What are your thoughts on adding a function of arity two that computes the distance between two points?

    def dist(a, b):
        return math.sqrt((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2)

**Comment by Maltysen** [comment]
You don't need an explicit distance function. `abs(aj+b)` is enough once we add complex numbers.

**Comment by orlp** [comment]
That's a good point.
