### ISSUE TITLE
String ending with a point screws up Q

### ISSUE THREAD

**Issue by jakobkogler** [isaacg1/pyth#73]
Title says it all. Take a look at this code. 

    @"abc."Q

It compiles down to 

    Pprint("\n",lookup("abc.",Q=copy()))

I guess there's something wrong with the parsing of the new two-letter commands (`.a`, `.b`, ...)

**Comment by orlp** [comment]
The bug lies in `prepend_parse`, I believe.

**Comment by isaacg1** [comment]
Fixed.
