### ISSUE TITLE
Get rid of `0x` and `0b`

### ISSUE THREAD

**Issue by jakobkogler** [isaacg1/pyth#74]
`.b` or `.H` are quite handy, but they return the number with the nasty prefix. (E.g. `.b5` returns `0b101`). Any reason why these prefixes are used? In golfing prefixes are usually unwanted.

**Comment by isaacg1** [comment]
Well, @orlp was the one who thought they should be used. Orlp, what was the reasoning behind that?

**Comment by orlp** [comment]
@isaacg1 I don't recall advocating for or against the prefixes. I'd be ok with them being removed.

**Comment by isaacg1** [comment]
Sorry about that, then. I must have misremembered. I'll make the change.
