### ISSUE TITLE
Pyth needs a guide for new users

### ISSUE THREAD

**Issue by isaacg1** [isaacg1/pyth#75]
It's time to write a guide for people who want to learn how to use Pyth.

Topics:

* Basics

 * Setting up Pyth

 * Literals

     * Numbers

     * Strings

 * Functions

     * Arity

 * Variables

* Advanced

 * Reading the Docs

 * Statements

 * Lambda functions

 * `.`

 * Autoinitializers

 * Reading error output

Anything else people think should be in there? Should not be in there?

**Comment by jakobkogler** [comment]
- Lists (also mention tuples, dict and set, but not in depth) 
 - Flow Control Statements (Loops and If/Else)

 - Functional programming (I guess that's what you mean by Lambda functions)

 - Preassigned variables

Rename Autoinitializers into Reading from STDIN

`.` shouldn't be an own chapter. Mentioning it during functions suffices.

**Comment by orlp** [comment]
@jakobkogler  There are other autoinitializers than just STDIN, for example `JK`.

**Comment by isaacg1** [comment]
Lambda functions means `m`, `f`, `u`, `o`, `.e`

**Comment by Maltysen** [comment]
I actually was writing this before, didn't get that far in and don't have `.`, but it should suffice as a new users guide. Have a look at it. I'm using sphinx. https://drive.google.com/file/d/0B0qkKIzGc0QicWxKVzdjcUxDSGc/view?usp=sharing

Use the command `sphinx build html` to build. We would put it up on readthedocs enventually.

**Comment by isaacg1** [comment]
@Maltysen This is great! If it's alright with you I'll start with this, then add more stuff in, spell check, etc. then incorporate it into the repo.

**Comment by isaacg1** [comment]
Implemented. Comments/additions are welcome.

**Comment by isaacg1** [comment]
Currently it's just a tutorial, but I'll be adding the documentation element to it as well over time.
