### ISSUE TITLE
Purge tuples from Pyth.

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#76]
I think we should purge tuples entirely from Pyth. They hold no advantage over lists in a golfing language.

Probably the easiest way to do this is to make sure no operation in Pyth ever produces a tuple, and if it does to turn to turn it into a list.

We will have to turn lists into tuples where required (e.g. dictionary keys), but we already had to do that anyway.

This also frees up `(`, maybe we can do something interesting with it.

**Comment by Maltysen** [comment]
Note that we will then have to do tuple -> list on `v` when used for input because `a,b` without the parens is a valid format for tuples but not for lists and that is a common input format.

**Comment by isaacg1** [comment]
This has been implemented, for the most part. `(` still exists, and `v` can still return tuples, but almost everything is lists now.
