### ISSUE TITLE
Add a rational type.

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#77]
I think a rational type is long overdue in Pyth. It would require a lot of work to implement it properly with everything, and would require a few support functions, just like complex numbers.

We might be able to share design decisions / functions used with complex numbers.

**Comment by isaacg1** [comment]
https://docs.python.org/3.1/library/fractions.html

This is the documentation involved.

**Comment by isaacg1** [comment]
I'm not planning on doing this.

**Comment by Maltysen** [comment]
I already had the code for it btw, remember. It was a combination of fraction and decimal.
