### ISSUE TITLE
Show code-length immediatly (Online Compiler)

### ISSUE THREAD

**Issue by jakobkogler** [isaacg1/pyth#84]
This bugged me for quite a while. 

When follow a link to the Pyth Compiler/Executer (e.g. [this link][0]), the code length shows `0`. Only when you manipulate the code, the code length gets updated to the correct length. 

 [0]: https://pyth.herokuapp.com/?code=Ksm%3E%2B0jCd16_2zJ%3F%2ChKeKQmxFdCcK2%3DKsmmxFkC%2CdJc%3FtPKQK2smCid16c%3FKQ%2B%2BhJKeJ2&input=G0lf%0A0&debug=0

**Comment by orlp** [comment]
While we're talking about the online interpreter, could the textbox please use a fixed-width font?

**Comment by gcq** [comment]
The fixed-width issue is one line of CSS away: `font-family: monospace;`
That should use the default monospaced font of the current system. I can PR if you want.
