### ISSUE TITLE
Make assignment an expression.

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#87]
This would be wildly useful. My proposal would be that `=` assigns something to a variable, and then returns the new value.

It would require some hacking, so for example this:

    =Y...

Would have to be turned into:

    assign("Y", ...)

And we'll probably have to do some funky stuff with `locals()`/`globals()`. But it's definitely possible.

Note that we must make an exception for augmented assignment:

    +=Y...

Should become:

    augmented_assign("Y", "+", ...)

To differentiate between augmented assignment, and assignment in a bigger expression we should also introduce `.=`, which acts exactly like `=`, except that it doesn't get parsed into augmented assignment. Maybe there is a smarter way to do it - I haven't given it much thought.

**Comment by isaacg1** [comment]
This sounds good. However, to implement this I'll need a character combination which corresponds to the `assign` function.  I'll make that `.~`.

**Comment by orlp** [comment]
@isaacg1  I don't understand, why not use `=` for assign?

**Comment by isaacg1** [comment]
`=` is the sugared assign. `.~` takes a string and updates its entry in globals and locals.

**Comment by isaacg1** [comment]
Question: should `=` print by default? I'm guessing no.

**Comment by orlp** [comment]
@isaacg1  I don't see the need for `.~` in this. You can just make this entry in `c_to_i`, no?

    '=':  (('assign(\'', '\', ', ')'), 2),

**Comment by orlp** [comment]
@isaacg1  Indeed, `=` at block scope should not print IMO.

**Comment by isaacg1** [comment]
That won't convert the first argument to a string.

**Comment by orlp** [comment]
@isaacg1 Yes it will, notice the `\'`s.

**Comment by isaacg1** [comment]
Hm. Hadn't considered that possibility. It should work.

**Comment by isaacg1** [comment]
I tried implementing this, and assigning to globals() inside assign isn't working - the program ignores the change. However, assigning to globals() inside the pyth itself works fine. I'm not sure what to do. Is there some way to get a reference to the local environment of the pyth expression itself?

**Comment by orlp** [comment]
@isaacg1 Make a new dictionary called "variables". Pre-load it with the values that Pyth supports (`k`, `d`, `Z`, etc). Then instead of using `exec` to execute the Pyth use `exec(..., variables)`.

**Comment by isaacg1** [comment]
Ah - so then modifying `variables` updates the appropriate variable?

**Comment by orlp** [comment]
@isaacg1  I presume so.

I just realized `variables` must also contain every function called from within Pyth.

**Comment by isaacg1** [comment]
That's ugly, but it might work.

**Comment by orlp** [comment]
@isaacg1  You might also initialize `variables` by doing `variables.update(globals())`, if I'm not mistaken. But that's kinda hacky, and in the long run manually inserting things into variables is probably cleaner.

**Comment by isaacg1** [comment]
Yeah, building `environment` manually is a reasonably solution. I'd call it environment over variables if it's going to have all sorts of functions in it too.

**Comment by orlp** [comment]
@isaacg1 Fair enough. This should also be able to harden the online security, if I'm not mistaken.

**Comment by isaacg1** [comment]
It probably would. I'll look into this.

**Comment by isaacg1** [comment]
I've tested out the variables system in mini-scale, and it works, so I'm going to start implementing it.

**Comment by isaacg1** [comment]
Implemented.
