### ISSUE TITLE
Leading zeroes in number constants could be split up.

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#89]
There is never a valid reason in Pyth to write either `023`, `0042` or `0.23` to my knowledge.

So my suggestion is that `023` could be the same as `0\n23`. Often you can use `Z` to alleviate this, but something you use `Z` for something else. This is just a very minor thing though.

An argument against this is that it might be confusing, and if we're ever going to dynamically allow compiling strings as Pyth from within Pyth then leading zeroes might be in input data and produce incorrect results.

**Comment by isaacg1** [comment]
Good idea. I'll implement this.

**Comment by isaacg1** [comment]
Implemented.
