### ISSUE TITLE
Bringing rle back

### ISSUE THREAD

**Issue by jakobkogler** [isaacg1/pyth#93]
When the rle (run length encoding) function was added to Pyth, I was not really in favor of it. Because I didn't see any usecases. 

But I the last time, quite a few answers to challenges on PPCG would have benefited by rle. Like [Identify card half](http://codegolf.stackexchange.com/questions/49747/identify-card-half) or [Road-Length Encoding](http://codegolf.stackexchange.com/questions/49307/road-length-encoding). 

How about bringing rle back and adding rld (run length decoding)?

**Comment by isaacg1** [comment]
Yeah, I was noticing that too. I was thinking of adding this to `r`'s processing library, but making `r` work on all collection types. `r_8` and `r_9` for the pair of them.

**Comment by isaacg1** [comment]
Completed.
