### ISSUE TITLE
Sorted Partitions

### ISSUE THREAD

**Issue by jakobkogler** [isaacg1/pyth#96]
Because of [this PPCG question](http://codegolf.stackexchange.com/questions/49943/maximum-concatenated-product#49943). 

How about a function, that returns all partitions of a string? By partition I mean the following: 

    Partitions("abc") = [["a", "b", "c"], ["ab", "c"], ["abc"], ["a", "bc"]]

So the elements should stay in order. It simply splits the string in all possible ways. Is there a special name for this kind of partitions?

The same thing should also work on sequences, like a list. And on numbers, where the number get's converted into a string, the partitions are computed and then mapped onto strings. 

    Partitions(1234) = [[1,2,3,4], [12,3,4], [12,34], [123,4], [1234], [1,23,4], [1,234],[1,2,34]]

I can implement this in the next days. Just post it here to see, what you think about this. This functionality is quite specific, but I have seen could also be useful for other questions like [this](http://codegolf.stackexchange.com/questions/49922/ways-to-arrange-the-integers-1-to-9-with-operators-so-that-the-result-is-100). And I currently don't see a nice way to implement such a thing in Pyth right now. The only thing that cames to mind is something similar like in this [answer](http://codegolf.stackexchange.com/questions/47926/sorted-lexical-partition-of-a-number/47937#47937), which is really really long.

**Comment by isaacg1** [comment]
Seems like a reasonable thing to add. I'm not sure about the last one, what should happen when called on numbers. Another reasonable alternative is the integer partition function: https://en.wikipedia.org/wiki/Partition_%28number_theory%29

**Comment by isaacg1** [comment]
Are you still planning on implementing this, or should I?

**Comment by jakobkogler** [comment]
Sorry for the delay, I will implement it right now.

**Comment by isaacg1** [comment]
No worries, take your time.

**Comment by jakobkogler** [comment]
Can be closed now. Implemented in #104
