### ISSUE TITLE
Augmented assignment order should be flipped.

### ISSUE THREAD

**Issue by orlp** [isaacg1/pyth#97]
Now that assignment is an expression the following isn't unambiguous anymore:

    +=ZT1

This could mean "Assign T to Z and return Z + 1", or it could mean "Add T to Z and print 1".

I'd suggest that we swap the ordering for augmented assignment:

    =+ZT1

There is only one interpretation possible for this - `Z += T; print(1)`.

**Comment by isaacg1** [comment]
This is a good idea. Also, I'd like to restructure how syntactic sugar works. I'm going to move it from `data.py` to `pyth.py`.

**Comment by isaacg1** [comment]
One edge case is that to continue to allow tuple assignment, we should not apply the sugaring to `,`.

**Comment by isaacg1** [comment]
Implemented.
